version: '3.8'

services:
  smart-storage:
    # Build the image from the Dockerfile in the current directory
    build: .
    # Give the container a friendly name
    container_name: smart-storage-manager
    # Ensure the container restarts automatically if it stops or the server reboots
    privileged: true
    restart: unless-stopped
    ports:
      # Map port 5001 on your host machine to port 5001 inside the container
      - "5001:5001"
    env_file:
      - .env
    volumes:
      # --- Configuration & Persistent Data ---
      # Mount your .env file for configuration. 'ro' means read-only.
      #- .env:/app/.env:ro
      # Create a local 'data' folder to store settings.json and logs persistently.
      - ./data:/app/backend/data
      - /path to env/.env:/app/backend/.env:ro
    
networks:
  app-network:
    driver: bridge